### ISSUE TITLE
Receiving Error with Upgrade to Bodi 1.5 via NuGet

### ISSUE THREAD

**Issue by jmodrzynski** [SpecFlowOSS/BoDi#38]
We updated to the latest Bodi version 1.5 yesterday and are receiving this error when running tests:

`OneTimeSetUp: System.MissingMethodException : Method not found: 'Void BoDi.ObjectContainer.RegisterTypeAs(System.String)'`

Downgrading back to version 1.4.1 fixes the issue.

**Comment by tzongithub** [comment]
If you want to try the updated BoDi with SpecFlow please update SpecFlow to v3.7.1-beta. It will use an alpha version of BoDi 1.5 then. The non-beta version of SpecFlow 3.7 with BoDi 1.5 is coming soon.

**Comment by tzongithub** [comment]
SpecFlow 3.7.13 has been released with BoDi 1.5.0. This error should not occur if you update both packages.
